dist: xenial

sudo: required

services:
  - docker

language: python

python:
  - '3.7'

env:
  global:
    - NOMAD_VERSION="0.9.0"
    - TESTING_MOCK_VM="true"

before_install:
  - curl -L -o /tmp/nomad_${NOMAD_VERSION}_linux_amd64.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip
  - yes | unzip -d /tmp /tmp/nomad_${NOMAD_VERSION}_linux_amd64.zip

install:
  - pip install pipenv
  - pipenv install

script:
  - /tmp/nomad agent -dev -node pynomad1 > /tmp/nomad.log 2>&1 &
  - sleep 60
  - travis_wait 1 pipenv run pytest

after_failure:
  - cat /tmp/nomad.log
